function getUrlVars(){for(var b=[],a,d=window.location.href.slice(window.location.href.indexOf("?")+1).split("&"),c=0;c<d.length;c++)a=d[c].split("="),b.push(a[0]),b[a[0]]=a[1];return b}function addChannel(){var b=/^[-_a-zA-Z0-9]+$/;if(getUrlVars().ch)var a=getUrlVars().ch.match(b);a!=null&&(a=$('input[name="channel-history"]').val()+$("form").attr("id")+" "+$("form").attr("name")+" channel: "+a+" || ",$('input[name="channel-history"]').val(a))}
function popByEmail(b,a,d,c){var f=0,b="<C_EmailAddress>"+b+"</C_EmailAddress>",e=(new Date).getMilliseconds(),g;if(typeof elqCurE!="undefined")$.getScript(elqCurE+"?pps=50&siteid="+elqSiteID+"&DLKey="+d+"&DLLookup="+b+"&ms="+e,function(){for(i in a)g=GetElqContentPersonalizationValue(a[i]),g!=""&&f++,$("#field"+i).val(g);typeof c=="function"&&c();return f});else return alert("Error: elqCurE or elqPPS undefined, include eloqua tracking scripts in head javascript"),0}
(function($){jQuery.fn.enterToTab=function(){return this.each(function(){$(this).bind("keypress",function(a){a.keyCode=="13"&&(a.preventDefault(),a=$(":focusable"),a.eq(a.index(this)+1).focus().select())})})};$.extend($.expr[":"],{focusable:function(a){var d=a.nodeName.toLowerCase(),c=$.attr(a,"tabindex");return(/input|select|textarea|button|object/.test(d)?!a.disabled:"a"==d||"area"==d?a.href||!isNaN(c):!isNaN(c))&&!$(a)["area"==d?"parents":"closest"](":hidden").length}})})(jQuery);
function prePop(b,a,d,c){$("input").not('input[type="submit"]').enterToTab();$("select").enterToTab();$("textarea").enterToTab();var f=0,e=$("#field0").val();GetElqContentPersonalizationValue=function(a){return a=="C_EmailAddress"?e=$("#field0").val():""};if(e==""){if(typeof elqCurE!="undefined"){var g=(new Date).getMilliseconds();$.getScript(elqCurE+"?pps=50&siteid="+elqSiteID+"&DLKey="+a+"&DLLookup=&ms="+g,function(){e=GetElqContentPersonalizationValue("V_Email_Address");return f=popByEmail(e,b,
d,c)})}}else return f=popByEmail(e,b,d,c)}function skipCondition(b){var a="#field"+b.depends;switch(b.operator){case "eq":return $(a).val()==b.condition?1:0;case "neq":return $(a).val()!=b.condition?1:0;case "contains":return patt=RegExp(b.condition,"i"),patt.test($(a).val())?1:0;case "always":return 1;default:return $(a).val()==b.condition?1:0}}function skipField(b){$("#formElement"+b).hide();$("#field"+b).rules("remove")}
function skipIfNotShown(b,a){var d=0;for(x in b)if(x==a){var c=b[x];for(y in c)c[y].action=="show"&&skipCondition(c[y])&&(d=1)}return d?0:(skipField(a),1)}function skipIfHidden(b,a){var d=0;for(x in b)if(x==a){var c=b[x];for(y in c)c[y].action=="hide"&&skipCondition(c[y])&&(d=1)}return d?(skipIfNotShown(b,a),1):0}
function proProgress(b,a,d,c,f){var e=0;for(i=0;i<a-1;i++)$("#formElement"+i).show();for(i=0;i<c;i++)$("#field"+i).val()==""&&e++;for(i=c;i<a-1;i++)if($("#field"+i).val()!="")skipIfNotShown(f,i)||e++;else if(e<d){c=0;for(x in f)x==i&&(c=1);c?skipIfHidden(f,i)||(e++,$("#field"+i).change(function(){var a=$(this).attr("id").replace("field","");f[a]={1:{action:"show",depends:"",operator:"always",condition:""}}})):(e++,f[i]={1:{action:"show",depends:"",operator:"always",condition:""}})}else skipIfNotShown(f,
i)||e++;e==0&&$("#"+b).submit();return f}
function progressiveProfile(b,a,d,c,f,e,g,h){var o=[];$.extend(!0,o,g);$("#"+d).validate(g);var l=0,j="formElement0";for(i=0;i<100;i++)j="formElement"+i,document.getElementById(j)!=null&&l++;h=proProgress(d,l,b,a,h);$("#field0").change(function(){$.extend(!0,g,o);for(i in c){var q=$("#field"+i).attr("name");for(field in g.rules)field==q&&$("#field"+i).rules("add",g.rules[q])}prePop(c,f,e,function(){addChannel();h=proProgress(d,l,b-1,a,h)})});var j=[],p=1;for(m in h)for(n in h[m]){var k=h[m][n].depends,
p=1;for(i in j)j[i]==k&&(p=0);p==1&&k!=""&&k!=0&&j.push(k)}for(i in j)k=j[i],$("#field"+k).change(function(){$.extend(!0,g,o);for(i in c){var e=$("#field"+i).attr("name");for(field in g.rules)field==e&&$("#field"+i).rules("add",g.rules[e])}e=$(this).attr("id");e=e.replace("field","");h[e]={1:{action:"show",depends:"",operator:"always",condition:""}};h=proProgress(d,l,b,a,h)})};