var debugProgressPro=0,progressProAutoSubmit=0,progressProValidator=0;function getUrlVars(){for(var c=[],b,a=window.location.href.slice(window.location.href.indexOf("?")+1).split("&"),d=0;d<a.length;d++)b=a[d].split("="),c.push(b[0]),c[b[0]]=b[1];return c}
function addChannel(c,b){debugProgressPro&&console.log("calling addchannel");var a=/^[-_a-zA-Z0-9]+$/;if(getUrlVars().ch)var d=getUrlVars().ch.match(a);null!=d&&(d=$("#"+c+' input[name="'+b+'"]').val()+c+" "+$("#"+c).attr("name")+" channel: "+d+" || ",$("#"+c+' input[name="'+b+'"]').val(d))}
function popByEmail(c,b,a,d,e){debugProgressPro&&console.log("populating fields by email "+b);for(i in a)$("#"+c+' [name="'+a[i]+'"]').val("");"function"==typeof e&&(debugProgressPro&&console.log("calling callback function: "+e),e());if(""!=b){var f;SetElqContent=function(){debugProgressPro&&console.log("called SetElqContent");for(i in a)f=GetElqContentPersonalizationValue(a[i]),debugProgressPro&&console.log("setting field "+a[i]+" to "+f),$("#"+c+' [name="'+a[i]+'"]').val(f);"function"==typeof e&&
(debugProgressPro&&console.log("calling callback function: "+e),e())};_elqQ.push(["elqDataLookup",d,"<C_EmailAddress>"+b+"</C_EmailAddress>"])}}
(function(c){jQuery.fn.enterToTab=function(){return this.each(function(){c(this).bind("keypress",function(b){"13"==b.keyCode&&(b.preventDefault(),b=c(":focusable"),b.eq(b.index(this)+1).focus().select())})})};c.extend(c.expr[":"],{focusable:function(b){var a=b.nodeName.toLowerCase(),d=c.attr(b,"tabindex");return(/input|select|textarea|button|object/.test(a)?!b.disabled:"a"==a||"area"==a?b.href||!isNaN(d):!isNaN(d))&&!c(b)["area"==a?"parents":"closest"](":hidden").length}})})(jQuery);
function prePop(c,b,a,d,e,f,k){debugProgressPro&&console.log("calling prepop");$("#"+c+" input").not('input[type="submit"]').enterToTab();$("#"+c+" select").enterToTab();$("#"+c+" textarea").enterToTab();var l=$("#"+c+' [name="'+e+'"]').val();GetElqContentPersonalizationValue=function(a){return a==e?l=$("#"+c+' [name="'+e+'"]').val():""};debugProgressPro&&console.log("initial email = "+l);""==l&&(debugProgressPro&&console.log("no email"),"undefined"!=typeof _elqQ&&(SetElqContent=function(){debugProgressPro&&
console.log("calling setElqContent");l=GetElqContentPersonalizationValue(f);popByEmail(c,l,b,d,k);debugProgressPro&&console.log("after cookie lookup, email = "+l)},debugProgressPro&&console.log("calling elq js"),_elqQ.push(["elqDataLookup",a,""])));popByEmail(c,l,b,d,k)}
function skipCondition(c,b){var a="#"+c+' [name="'+b.depends+'"]';if("radio"==$(a).attr("type"))switch(a=b.depends,b.operator){case "eq":return $("#"+c+' [name*="'+a+'"][type=radio]:checked').val()==b.condition?1:0;case "neq":return $("#"+c+' [name*="'+a+'"][type=radio]:checked').val()!=b.condition?1:0;case "contains":return patt=new RegExp(b.condition,"i"),patt.test($("#"+c+' [name*="'+a+'"][type=radio]:checked').val())?1:0;case "always":return 1;default:return $("#"+c+' [name*="'+a+'"][type=radio]:checked').val()==
b.condition?1:0}else switch(b.operator){case "eq":return $(a).val()==b.condition?1:0;case "neq":return $(a).val()!=b.condition?1:0;case "contains":return patt=new RegExp(b.condition,"i"),patt.test($(a).val())?1:0;case "always":return 1;default:return $(a).val()==b.condition?1:0}}function skipField(c,b){debugProgressPro&&console.log("skipping field "+b);$("#"+c+' p:has([name="'+b+'"])').hide();$("#"+c+' [name="'+b+'"]').rules("remove")}
function skipIfNotShown(c,b,a){var d=0;for(x in b)if(x==a){var e=b[x];for(y in e)"show"==e[y].action&&skipCondition(c,e[y])&&(d=1)}if(d)return 0;skipField(c,a);return 1}function skipIfHidden(c,b,a){debugProgressPro&&console.log("calling skipIfHidden for field "+a);var d=0;for(x in b)if(x==a){var e=b[x];for(y in e)"hide"==e[y].action&&skipCondition(c,e[y])&&(d=1)}return d?(skipIfNotShown(c,b,a),1):0}
function proProgress(c,b,a,d,e){var f=[];$.extend(!0,f,d);nfields=e.length;debugProgressPro&&(console.log("calling proProgress, nfields="+nfields+" sd = "+b+" ad = "+a+" Skip options:"),console.dir(d));var k=0;for(i in e)$("#"+c+' p:has([name="'+e[i]+'"])').show();debugProgressPro&&console.log("all fields shown: "+e);for(i=0;i<a;i++)""==$("#"+c+' [name="'+e[i]+'"]').val()&&k++;for(i=a;i<nfields;i++)if(""!=$("#"+c+' [name="'+e[i]+'"]').val())skipIfNotShown(c,d,e[i])||k++;else if(k<b){a=0;for(x in d)x==
e[i]&&(a=1);a?skipIfHidden(c,d,e[i])||(k++,$("#"+c+' [name="'+e[i]+'"]').change(function(){var a=$(this).attr("name");f[a]={1:{action:"show",depends:"",operator:"always",condition:""}}})):(k++,f[e[i]]={1:{action:"show",depends:"",operator:"always",condition:""}})}else skipIfNotShown(c,d,e[i])||k++;debugProgressPro&&console.log("number of open fields: "+k);0==k&&progressProAutoSubmit&&$("#"+c).submit();return f}
function progressiveProfile(c,b,a,d,e,f,k,l,r,g,h){debugProgressPro&&(console.log("progressiveProfile called, skip options: "),console.dir(h));oldValOptions=[];oldSkipOptions=[];$.extend(!0,oldValOptions,g);$.extend(!0,oldSkipOptions,h);if(0===progressProValidator)debugProgressPro&&(console.log("validating form with validation options: "),console.dir(g)),progressProValidator=$("#"+a).validate(g);else for(i in d)for(field in f=d[i],g.rules)field==f&&($("#"+a+' [name="'+d[i]+'"]').rules("add",g.rules[f]),
debugProgressPro&&console.log("added rules: "+g.rules[f]+" to field "+field));if(debugProgressPro)for(i in d)for(field in f=d[i],g.rules)field==f&&(console.log("field "+field+" has rules:"),console.dir($("#"+a+' [name="'+d[i]+'"]').rules()));debugProgressPro&&console.log("calling proProgress, old skip options:");debugProgressPro&&console.dir(oldSkipOptions);h=proProgress(a,c,b,oldSkipOptions,d);$("#"+a+' [name="'+l+'"]').change(function(){$.extend(!0,h,oldSkipOptions);$.extend(!0,g,oldValOptions);
popByEmail(a,$(this).val(),e,k,function(){for(i in d){var e=d[i];for(field in g.rules)field==e&&($("#"+a+' [name="'+d[i]+'"]').rules("add",g.rules[e]),debugProgressPro&&console.log("added rules: "+g.rules[e]+" to field "+field))}r&&addChannel(a,r);h=proProgress(a,c-1,b,oldSkipOptions,d)})});f=[];var q=1;for(m in h)for(n in h[m]){var p=h[m][n].depends,q=1;for(i in f)f[i]==p&&(q=0);1==q&&""!=p&&p!=l&&f.push(p)}for(i in f)p=f[i],"radio"==$("#"+a+' [name="'+p+'"]').attr("type")?$("#"+a+' input[name="'+
p+'"]').change(function(){$.extend(!0,g,oldValOptions);for(i in d){var e=d[i];for(field in g.rules)field==e&&($("#"+a+' [name="'+d[i]+'"]').rules("add",g.rules[e]),debugProgressPro&&console.log("added rules: "+g.rules[e]+" to field "+field))}e=$(this).attr("name");h[e]={1:{action:"show",depends:"",operator:"always",condition:""}};h=proProgress(a,c,b,h,d)}):$("#"+a+' [name="'+p+'"]').change(function(){debugProgressPro&&console.log("field changed");$.extend(!0,g,oldValOptions);for(i in d){var e=d[i];
for(field in g.rules)field==e&&($("#"+a+' [name="'+d[i]+'"]').rules("add",g.rules[e]),debugProgressPro&&console.log("added rules: "+g.rules[e]+" to field "+field))}e=$(this).attr("name");h[e]={1:{action:"show",depends:"",operator:"always",condition:""}};h=proProgress(a,c,b,h,d)})};
